### ISSUE TITLE
Update to sbt 1.x.x

### ISSUE THREAD

**Issue by Asamsig** [BorisNaguet/sbt-cxf-wsdl2java#14]
Would be great if this plugin could be updated to 1.x.x

**Comment by BorisNaguet** [comment]
Hello,

Lot's of plugins are still not migrated:
https://github.com/sbt/sbt/wiki/sbt-1.x-plugin-migration

So that would need cross-building to support 0.13.6 at least:
http://www.scala-sbt.org/0.13/docs/sbt-0.13-Tech-Previews.html#sbt-cross-building

Migration guide:
http://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html

**Comment by Asamsig** [comment]
I've tested again with the release version, on both 0.13.17 and 1.1.1, both work fine now. 🎉
